version: '3.4'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Simpress@123"
      MSSQL_PID: Express
      
    ports:
      - "1433:1433"
   

  simpress.product.api:
    image: ${DOCKER_REGISTRY-}simpressproductapi
    build:
      context: .
      dockerfile: Simpress.Product.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql-server
